name: CatTownsend
favicon: null
layout_spectrum: 0.9826996454503387
typography_spectrum: 0.8210577522404492
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.22785231610760093
  lightness: 0.6267003647517413
  saturation: 0.6379802259616554
  rhythmicContrast: 0.8000135764013976
purpose: []
