name: CatTownsend
favicon: null
layout_spectrum: 0.99871
typography_spectrum: 0.8210577522404492
title: Cat Townsend
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
